default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: dasha
  password:

development:
  <<: *default
  database: workout_buddy_development

test:
  <<: *default
  database: workout_buddy_test

production:
  <<: *default
  database: workout_buddy_production
