default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: dasha
  password:

development:
  <<: *default
  database: workout_buddy_development

test:
  <<: *default
  database: workout_buddy_test

production:
  <<: *default
  database: workout_buddy_production


# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3
#
# production:
#   <<: *default
#   database: db/production.sqlite3
